	.file	"Lab5_Grp14_code.cpp"
	.text
	.section	.text$_ZnwyPv,"x"
	.linkonce discard
	.globl	_ZnwyPv
	.def	_ZnwyPv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZnwyPv
_ZnwyPv:
.LFB156:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZdlPvS_,"x"
	.linkonce discard
	.globl	_ZdlPvS_
	.def	_ZdlPvS_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZdlPvS_
_ZdlPvS_:
.LFB158:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
.lcomm _ZStL8__ioinit,1,1
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implD1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implD1Ev
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implD1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implD1Ev
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implD1Ev:
.LFB2929:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaISt6vectorI7Point3DSaIS0_EEED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EEC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EEC2Ev
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EEC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EEC2Ev
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EEC2Ev:
.LFB2930:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implC1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEC1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEC1Ev
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEC1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEC1Ev
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEC1Ev:
.LFB2933:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EEC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev
_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev:
.LFB2939:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2Ev
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2Ev
_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2Ev:
.LFB2940:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EEC1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EEC1Ev
	.def	_ZNSt6vectorI7Point3DSaIS0_EEC1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EEC1Ev
_ZNSt6vectorI7Point3DSaIS0_EEC1Ev:
.LFB2943:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.def	__main;	.scl	2;	.type	32;	.endef
	.section .rdata,"dr"
	.align 8
.LC0:
	.ascii "Enter the number of test_cases\12\0"
.LC1:
	.ascii "\12\0"
	.text
	.globl	main
	.def	main;	.scl	2;	.type	32;	.endef
	.seh_proc	main
main:
.LFB2923:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$200, %rsp
	.seh_stackalloc	200
	leaq	192(%rsp), %rbp
	.seh_setframe	%rbp, 192
	.seh_endprologue
	call	__main
	pxor	%xmm0, %xmm0
	movaps	%xmm0, -48(%rbp)
	movq	%xmm0, -32(%rbp)
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEC1Ev
	leaq	.LC0(%rip), %rax
	movq	%rax, %rdx
	movq	.refptr._ZSt4cout(%rip), %rax
	movq	%rax, %rcx
.LEHB0:
	call	_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc
	leaq	-20(%rbp), %rax
	movq	%rax, %rdx
	movq	.refptr._ZSt3cin(%rip), %rax
	movq	%rax, %rcx
	call	_ZNSirsERi
	movl	$0, -4(%rbp)
	jmp	.L11
.L14:
	leaq	-24(%rbp), %rax
	movq	%rax, %rdx
	movq	.refptr._ZSt3cin(%rip), %rax
	movq	%rax, %rcx
	call	_ZNSirsERi
.LEHE0:
	pxor	%xmm0, %xmm0
	movaps	%xmm0, -80(%rbp)
	movq	%xmm0, -64(%rbp)
	leaq	-80(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EEC1Ev
	movl	$0, -8(%rbp)
	jmp	.L12
.L13:
	leaq	-92(%rbp), %rax
	movq	%rax, %rdx
	movq	.refptr._ZSt3cin(%rip), %rax
	movq	%rax, %rcx
.LEHB1:
	call	_ZNSirsERi
	movq	%rax, %rcx
	leaq	-92(%rbp), %rax
	addq	$4, %rax
	movq	%rax, %rdx
	call	_ZNSirsERi
	movq	%rax, %rcx
	leaq	-92(%rbp), %rax
	addq	$8, %rax
	movq	%rax, %rdx
	call	_ZNSirsERi
	leaq	-92(%rbp), %rdx
	leaq	-80(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE9push_backERKS0_
	addl	$1, -8(%rbp)
.L12:
	movl	-24(%rbp), %eax
	cmpl	%eax, -8(%rbp)
	jl	.L13
	leaq	-80(%rbp), %rdx
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE9push_backERKS2_
.LEHE1:
	leaq	-80(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EED1Ev
	addl	$1, -4(%rbp)
.L11:
	movl	-20(%rbp), %eax
	cmpl	%eax, -4(%rbp)
	jl	.L14
	movl	$0, -12(%rbp)
	jmp	.L15
.L18:
	movl	$0, -16(%rbp)
	jmp	.L16
.L17:
	movl	-12(%rbp), %eax
	movslq	%eax, %rdx
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
.LEHB2:
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy
	movq	%rax, %rcx
	movl	-16(%rbp), %eax
	cltq
	movq	%rax, %rdx
	call	_ZNSt6vectorI7Point3DSaIS0_EE2atEy
	movq	(%rax), %rdx
	movq	%rdx, -104(%rbp)
	movl	8(%rax), %eax
	movl	%eax, -96(%rbp)
	movl	-12(%rbp), %eax
	movslq	%eax, %rdx
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy
	movq	%rax, %rcx
	movl	-16(%rbp), %eax
	addl	$1, %eax
	cltq
	movq	%rax, %rdx
	call	_ZNSt6vectorI7Point3DSaIS0_EE2atEy
	movq	(%rax), %rdx
	movq	%rdx, -116(%rbp)
	movl	8(%rax), %eax
	movl	%eax, -108(%rbp)
	movq	-104(%rbp), %rax
	movq	%rax, -144(%rbp)
	movl	-96(%rbp), %eax
	movl	%eax, -136(%rbp)
	movq	-116(%rbp), %rax
	movq	%rax, -160(%rbp)
	movl	-108(%rbp), %eax
	movl	%eax, -152(%rbp)
	leaq	-160(%rbp), %rdx
	leaq	-144(%rbp), %rax
	movq	%rax, %rcx
	call	_Z13manhattanDist7Point3DS_
	movl	%eax, %edx
	movq	.refptr._ZSt4cout(%rip), %rax
	movq	%rax, %rcx
	call	_ZNSolsEi
	movq	%rax, %rcx
	leaq	.LC1(%rip), %rax
	movq	%rax, %rdx
	call	_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc
	addl	$1, -16(%rbp)
.L16:
	movl	-16(%rbp), %eax
	movslq	%eax, %rbx
	movl	-12(%rbp), %eax
	movslq	%eax, %rdx
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy
	movq	%rax, %rcx
	call	_ZSt4sizeISt6vectorI7Point3DSaIS1_EEEDTcldtfp_4sizeEERKT_
	subq	$1, %rax
	cmpq	%rax, %rbx
	setb	%al
	testb	%al, %al
	jne	.L17
	leaq	.LC1(%rip), %rax
	movq	%rax, %rdx
	movq	.refptr._ZSt4cout(%rip), %rax
	movq	%rax, %rcx
	call	_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc
.LEHE2:
	addl	$1, -12(%rbp)
.L15:
	movl	-20(%rbp), %eax
	cmpl	%eax, -12(%rbp)
	jl	.L18
	movl	$0, %ebx
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev
	movl	%ebx, %eax
	jmp	.L24
.L23:
	movq	%rax, %rbx
	leaq	-80(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EED1Ev
	jmp	.L21
.L22:
	movq	%rax, %rbx
.L21:
	leaq	-48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev
	movq	%rbx, %rax
	movq	%rax, %rcx
.LEHB3:
	call	_Unwind_Resume
.LEHE3:
.L24:
	addq	$200, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.def	__gxx_personality_seh0;	.scl	2;	.type	32;	.endef
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA2923:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE2923-.LLSDACSB2923
.LLSDACSB2923:
	.uleb128 .LEHB0-.LFB2923
	.uleb128 .LEHE0-.LEHB0
	.uleb128 .L22-.LFB2923
	.uleb128 0
	.uleb128 .LEHB1-.LFB2923
	.uleb128 .LEHE1-.LEHB1
	.uleb128 .L23-.LFB2923
	.uleb128 0
	.uleb128 .LEHB2-.LFB2923
	.uleb128 .LEHE2-.LEHB2
	.uleb128 .L22-.LFB2923
	.uleb128 0
	.uleb128 .LEHB3-.LFB2923
	.uleb128 .LEHE3-.LEHB3
	.uleb128 0
	.uleb128 0
.LLSDACSE2923:
	.text
	.seh_endproc
	.globl	_Z13manhattanDist7Point3DS_
	.def	_Z13manhattanDist7Point3DS_;	.scl	2;	.type	32;	.endef
	.seh_proc	_Z13manhattanDist7Point3DS_
_Z13manhattanDist7Point3DS_:
.LFB2944:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rsi
	.seh_pushreg	%rsi
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$16, %rsp
	.seh_stackalloc	16
	leaq	16(%rsp), %rbp
	.seh_setframe	%rbp, 16
	.seh_endprologue
	movq	%rcx, %rsi
	movq	%rdx, %rbx
	movl	(%rsi), %eax
	movl	(%rbx), %edx
	subl	%edx, %eax
	movl	%eax, %edx
	negl	%edx
	cmovns	%edx, %eax
	movl	%eax, %ecx
	movl	4(%rsi), %eax
	movl	4(%rbx), %edx
	subl	%edx, %eax
	movl	%eax, %edx
	negl	%edx
	cmovns	%edx, %eax
	addl	%eax, %ecx
	movl	8(%rsi), %eax
	movl	8(%rbx), %edx
	subl	%edx, %eax
	movl	%eax, %edx
	negl	%edx
	cmovns	%edx, %eax
	addl	%ecx, %eax
	movl	%eax, -4(%rbp)
	movl	-4(%rbp), %eax
	addq	$16, %rsp
	popq	%rbx
	popq	%rsi
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implC1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implC1Ev
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implC1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implC1Ev
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implC1Ev:
.LFB3261:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaISt6vectorI7Point3DSaIS0_EEEC2Ev
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE17_Vector_impl_dataC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaISt6vectorI7Point3DSaIS0_EEED2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaISt6vectorI7Point3DSaIS0_EEED2Ev
	.def	_ZNSaISt6vectorI7Point3DSaIS0_EEED2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaISt6vectorI7Point3DSaIS0_EEED2Ev
_ZNSaISt6vectorI7Point3DSaIS0_EEED2Ev:
.LFB3263:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev:
.LFB3266:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	16(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	subq	%rax, %rdx
	sarq	$3, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	movq	%rax, %rcx
	movq	16(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE12_Vector_implD1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3266:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3266-.LLSDACSB3266
.LLSDACSB3266:
.LLSDACSE3266:
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev:
.LFB3270:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rcx
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3270:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3270-.LLSDACSB3270
.LLSDACSB3270:
.LLSDACSE3270:
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EED1Ev,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1Ev
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1Ev
_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1Ev:
.LFB3274:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DEC2Ev
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaI7Point3DED2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaI7Point3DED2Ev
	.def	_ZNSaI7Point3DED2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaI7Point3DED2Ev
_ZNSaI7Point3DED2Ev:
.LFB3276:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaI7Point3DED1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaI7Point3DED1Ev
	.def	_ZNSaI7Point3DED1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaI7Point3DED1Ev
_ZNSaI7Point3DED1Ev:
.LFB3277:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev
_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev:
.LFB3279:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	16(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	subq	%rax, %rdx
	sarq	$2, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	movq	%rax, %rcx
	movq	16(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3279:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3279-.LLSDACSB3279
.LLSDACSB3279:
.LLSDACSE3279:
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EED1Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EED1Ev
	.def	_ZNSt6vectorI7Point3DSaIS0_EED1Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EED1Ev
_ZNSt6vectorI7Point3DSaIS0_EED1Ev:
.LFB3283:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rcx
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt8_DestroyIP7Point3DS0_EvT_S2_RSaIT0_E
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3283:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3283-.LLSDACSB3283
.LLSDACSB3283:
.LLSDACSE3283:
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EED1Ev,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE9push_backERKS0_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE9push_backERKS0_
	.def	_ZNSt6vectorI7Point3DSaIS0_EE9push_backERKS0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE9push_backERKS0_
_ZNSt6vectorI7Point3DSaIS0_EE9push_backERKS0_:
.LFB3284:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	16(%rax), %rax
	cmpq	%rax, %rdx
	je	.L37
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	24(%rbp), %rcx
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_
	movq	16(%rbp), %rax
	movq	8(%rax), %rax
	leaq	12(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, 8(%rax)
	jmp	.L39
.L37:
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE3endEv
	movq	%rax, %rdx
	movq	24(%rbp), %rcx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE17_M_realloc_insertIJRKS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_
.L39:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE9push_backERKS2_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE9push_backERKS2_
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE9push_backERKS2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE9push_backERKS2_
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE9push_backERKS2_:
.LFB3286:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	16(%rax), %rax
	cmpq	%rax, %rdx
	je	.L41
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	24(%rbp), %rcx
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_
	movq	16(%rbp), %rax
	movq	8(%rax), %rax
	leaq	24(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, 8(%rax)
	jmp	.L43
.L41:
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE3endEv
	movq	%rax, %rdx
	movq	24(%rbp), %rcx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_
.L43:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE2atEy:
.LFB3288:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE14_M_range_checkEy
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEixEy
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt4sizeISt6vectorI7Point3DSaIS1_EEEDTcldtfp_4sizeEERKT_,"x"
	.linkonce discard
	.globl	_ZSt4sizeISt6vectorI7Point3DSaIS1_EEEDTcldtfp_4sizeEERKT_
	.def	_ZSt4sizeISt6vectorI7Point3DSaIS1_EEEDTcldtfp_4sizeEERKT_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt4sizeISt6vectorI7Point3DSaIS1_EEEDTcldtfp_4sizeEERKT_
_ZSt4sizeISt6vectorI7Point3DSaIS1_EEEDTcldtfp_4sizeEERKT_:
.LFB3289:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE2atEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE2atEy
	.def	_ZNSt6vectorI7Point3DSaIS0_EE2atEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE2atEy
_ZNSt6vectorI7Point3DSaIS0_EE2atEy:
.LFB3290:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE14_M_range_checkEy
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EEixEy
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaISt6vectorI7Point3DSaIS0_EEEC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaISt6vectorI7Point3DSaIS0_EEEC2Ev
	.def	_ZNSaISt6vectorI7Point3DSaIS0_EEEC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaISt6vectorI7Point3DSaIS0_EEEC2Ev
_ZNSaISt6vectorI7Point3DSaIS0_EEEC2Ev:
.LFB3446:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEEC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE17_Vector_impl_dataC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE17_Vector_impl_dataC2Ev
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE17_Vector_impl_dataC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE17_Vector_impl_dataC2Ev
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE17_Vector_impl_dataC2Ev:
.LFB3449:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	$0, (%rax)
	movq	16(%rbp), %rax
	movq	$0, 8(%rax)
	movq	16(%rbp), %rax
	movq	$0, 16(%rax)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEED2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEED2Ev
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEED2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEED2Ev
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEED2Ev:
.LFB3452:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y:
.LFB3454:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	cmpq	$0, 24(%rbp)
	je	.L55
	movq	16(%rbp), %rax
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE10deallocateERS4_PS3_y
.L55:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv:
.LFB3455:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E,"x"
	.linkonce discard
	.globl	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E
	.def	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E
_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E:
.LFB3456:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EEEvT_S5_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaI7Point3DEC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaI7Point3DEC2Ev
	.def	_ZNSaI7Point3DEC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaI7Point3DEC2Ev
_ZNSaI7Point3DEC2Ev:
.LFB3459:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DEC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev
_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev:
.LFB3462:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	$0, (%rax)
	movq	16(%rbp), %rax
	movq	$0, 8(%rax)
	movq	16(%rbp), %rax
	movq	$0, 16(%rax)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorI7Point3DED2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorI7Point3DED2Ev
	.def	_ZNSt15__new_allocatorI7Point3DED2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorI7Point3DED2Ev
_ZNSt15__new_allocatorI7Point3DED2Ev:
.LFB3465:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y
_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y:
.LFB3467:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	cmpq	$0, 24(%rbp)
	je	.L64
	movq	16(%rbp), %rax
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaI7Point3DEE10deallocateERS1_PS0_y
.L64:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv:
.LFB3468:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt8_DestroyIP7Point3DS0_EvT_S2_RSaIT0_E,"x"
	.linkonce discard
	.globl	_ZSt8_DestroyIP7Point3DS0_EvT_S2_RSaIT0_E
	.def	_ZSt8_DestroyIP7Point3DS0_EvT_S2_RSaIT0_E;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt8_DestroyIP7Point3DS0_EvT_S2_RSaIT0_E
_ZSt8_DestroyIP7Point3DS0_EvT_S2_RSaIT0_E:
.LFB3469:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt8_DestroyIP7Point3DEvT_S2_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_
	.def	_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_
_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_:
.LFB3470:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE
	movq	%rax, %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DE9constructIS0_JRKS0_EEEvPT_DpOT0_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE3endEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE3endEv
	.def	_ZNSt6vectorI7Point3DSaIS0_EE3endEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE3endEv
_ZNSt6vectorI7Point3DSaIS0_EE3endEv:
.LFB3471:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	leaq	8(%rax), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_
	movq	-8(%rbp), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section .rdata,"dr"
.LC2:
	.ascii "vector::_M_realloc_insert\0"
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE17_M_realloc_insertIJRKS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE17_M_realloc_insertIJRKS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_
	.def	_ZNSt6vectorI7Point3DSaIS0_EE17_M_realloc_insertIJRKS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE17_M_realloc_insertIJRKS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_
_ZNSt6vectorI7Point3DSaIS0_EE17_M_realloc_insertIJRKS0_EEEvN9__gnu_cxx17__normal_iteratorIPS0_S2_EEDpOT_:
.LFB3472:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$104, %rsp
	.seh_stackalloc	104
	leaq	96(%rsp), %rbp
	.seh_setframe	%rbp, 96
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	32(%rbp), %rax
	leaq	.LC2(%rip), %r8
	movl	$1, %edx
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE12_M_check_lenEyPKc
	movq	%rax, -8(%rbp)
	movq	32(%rbp), %rax
	movq	(%rax), %rax
	movq	%rax, -16(%rbp)
	movq	32(%rbp), %rax
	movq	8(%rax), %rax
	movq	%rax, -24(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE5beginEv
	movq	%rax, -56(%rbp)
	leaq	-56(%rbp), %rdx
	leaq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxxmiIP7Point3DSt6vectorIS1_SaIS1_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKS9_SC_
	movq	%rax, -32(%rbp)
	movq	32(%rbp), %rax
	movq	-8(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy
	movq	%rax, -40(%rbp)
	movq	-40(%rbp), %rax
	movq	%rax, -48(%rbp)
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE
	movq	%rax, %rcx
	movq	-32(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rdx
	movq	-40(%rbp), %rax
	addq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaI7Point3DEE9constructIS0_JRKS0_EEEvRS1_PT_DpOT0_
	movq	$0, -48(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rbx
	leaq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	movq	(%rax), %rdx
	movq	-40(%rbp), %rcx
	movq	-16(%rbp), %rax
	movq	%rbx, %r9
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_
	movq	%rax, -48(%rbp)
	addq	$12, -48(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rbx
	leaq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	movq	(%rax), %rax
	movq	-48(%rbp), %rcx
	movq	-24(%rbp), %rdx
	movq	%rbx, %r9
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_
	movq	%rax, -48(%rbp)
	movq	32(%rbp), %rax
	movq	32(%rbp), %rdx
	movq	16(%rdx), %rdx
	subq	-16(%rbp), %rdx
	movq	%rdx, %rcx
	sarq	$2, %rcx
	movabsq	$-6148914691236517205, %rdx
	imulq	%rcx, %rdx
	movq	%rdx, %rcx
	movq	-16(%rbp), %rdx
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE13_M_deallocateEPS0_y
	movq	32(%rbp), %rax
	movq	-40(%rbp), %rdx
	movq	%rdx, (%rax)
	movq	32(%rbp), %rax
	movq	-48(%rbp), %rdx
	movq	%rdx, 8(%rax)
	movq	-8(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rdx
	movq	-40(%rbp), %rax
	addq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rdx, 16(%rax)
	nop
	addq	$104, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_
	.def	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_
_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_:
.LFB3476:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE
	movq	%rax, %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE3endEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE3endEv
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE3endEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE3endEv
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE3endEv:
.LFB3477:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	leaq	8(%rax), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_
	movq	-8(%rbp), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_:
.LFB3478:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$104, %rsp
	.seh_stackalloc	104
	leaq	96(%rsp), %rbp
	.seh_setframe	%rbp, 96
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	32(%rbp), %rax
	leaq	.LC2(%rip), %r8
	movl	$1, %edx
	movq	%rax, %rcx
.LEHB4:
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE12_M_check_lenEyPKc
	movq	%rax, -8(%rbp)
	movq	32(%rbp), %rax
	movq	(%rax), %rax
	movq	%rax, -16(%rbp)
	movq	32(%rbp), %rax
	movq	8(%rax), %rax
	movq	%rax, -24(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE5beginEv
	movq	%rax, -56(%rbp)
	leaq	-56(%rbp), %rdx
	leaq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxxmiIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKSB_SE_
	movq	%rax, -32(%rbp)
	movq	32(%rbp), %rax
	movq	-8(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE11_M_allocateEy
.LEHE4:
	movq	%rax, -40(%rbp)
	movq	-40(%rbp), %rax
	movq	%rax, -48(%rbp)
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE
	movq	%rax, %rcx
	movq	-32(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$3, %rax
	movq	%rax, %rdx
	movq	-40(%rbp), %rax
	addq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
.LEHB5:
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JRKS3_EEEvRS4_PT_DpOT0_
.LEHE5:
	movq	$0, -48(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rbx
	leaq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv
	movq	(%rax), %rdx
	movq	-40(%rbp), %rcx
	movq	-16(%rbp), %rax
	movq	%rbx, %r9
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_
	movq	%rax, -48(%rbp)
	addq	$24, -48(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rbx
	leaq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv
	movq	(%rax), %rax
	movq	-48(%rbp), %rcx
	movq	-24(%rbp), %rdx
	movq	%rbx, %r9
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_
	movq	%rax, -48(%rbp)
	movq	32(%rbp), %rax
	movq	32(%rbp), %rdx
	movq	16(%rdx), %rdx
	subq	-16(%rbp), %rdx
	movq	%rdx, %rcx
	sarq	$3, %rcx
	movabsq	$-6148914691236517205, %rdx
	imulq	%rcx, %rdx
	movq	%rdx, %rcx
	movq	-16(%rbp), %rdx
	movq	%rcx, %r8
	movq	%rax, %rcx
.LEHB6:
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y
.LEHE6:
	movq	32(%rbp), %rax
	movq	-40(%rbp), %rdx
	movq	%rdx, (%rax)
	movq	32(%rbp), %rax
	movq	-48(%rbp), %rdx
	movq	%rdx, 8(%rax)
	movq	-8(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$3, %rax
	movq	%rax, %rdx
	movq	-40(%rbp), %rax
	addq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rdx, 16(%rax)
	jmp	.L82
.L80:
	movq	%rax, %rcx
	call	__cxa_begin_catch
	cmpq	$0, -48(%rbp)
	jne	.L77
	movq	-32(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$3, %rax
	movq	%rax, %rdx
	movq	-40(%rbp), %rax
	addq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_
	jmp	.L78
.L77:
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rcx
	movq	-48(%rbp), %rdx
	movq	-40(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
.LEHB7:
	call	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EES3_EvT_S5_RSaIT0_E
.L78:
	movq	32(%rbp), %rax
	movq	-8(%rbp), %rcx
	movq	-40(%rbp), %rdx
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE13_M_deallocateEPS3_y
	call	__cxa_rethrow
.LEHE7:
.L81:
	movq	%rax, %rbx
	call	__cxa_end_catch
	movq	%rbx, %rax
	movq	%rax, %rcx
.LEHB8:
	call	_Unwind_Resume
	nop
.LEHE8:
.L82:
	addq	$104, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
	.align 4
.LLSDA3478:
	.byte	0xff
	.byte	0x9b
	.uleb128 .LLSDATT3478-.LLSDATTD3478
.LLSDATTD3478:
	.byte	0x1
	.uleb128 .LLSDACSE3478-.LLSDACSB3478
.LLSDACSB3478:
	.uleb128 .LEHB4-.LFB3478
	.uleb128 .LEHE4-.LEHB4
	.uleb128 0
	.uleb128 0
	.uleb128 .LEHB5-.LFB3478
	.uleb128 .LEHE5-.LEHB5
	.uleb128 .L80-.LFB3478
	.uleb128 0x1
	.uleb128 .LEHB6-.LFB3478
	.uleb128 .LEHE6-.LEHB6
	.uleb128 0
	.uleb128 0
	.uleb128 .LEHB7-.LFB3478
	.uleb128 .LEHE7-.LEHB7
	.uleb128 .L81-.LFB3478
	.uleb128 0
	.uleb128 .LEHB8-.LFB3478
	.uleb128 .LEHE8-.LEHB8
	.uleb128 0
	.uleb128 0
.LLSDACSE3478:
	.byte	0x1
	.byte	0
	.align 4
	.long	0

.LLSDATT3478:
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE17_M_realloc_insertIJRKS2_EEEvN9__gnu_cxx17__normal_iteratorIPS2_S4_EEDpOT_,"x"
	.linkonce discard
	.seh_endproc
	.section .rdata,"dr"
	.align 8
.LC3:
	.ascii "vector::_M_range_check: __n (which is %zu) >= this->size() (which is %zu)\0"
	.section	.text$_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE14_M_range_checkEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE14_M_range_checkEy
	.def	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE14_M_range_checkEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE14_M_range_checkEy
_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE14_M_range_checkEy:
.LFB3482:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	cmpq	%rax, 24(%rbp)
	setnb	%al
	testb	%al, %al
	je	.L85
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	movq	%rax, %rdx
	movq	24(%rbp), %rax
	movq	%rdx, %r8
	movq	%rax, %rdx
	leaq	.LC3(%rip), %rax
	movq	%rax, %rcx
	call	_ZSt24__throw_out_of_range_fmtPKcz
.L85:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEixEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEixEy
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEixEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEixEy
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EEixEy:
.LFB3483:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	(%rax), %rcx
	movq	24(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$3, %rax
	addq	%rcx, %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	.def	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv:
.LFB3484:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	subq	%rax, %rdx
	sarq	$2, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorI7Point3DSaIS0_EE14_M_range_checkEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorI7Point3DSaIS0_EE14_M_range_checkEy
	.def	_ZNKSt6vectorI7Point3DSaIS0_EE14_M_range_checkEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorI7Point3DSaIS0_EE14_M_range_checkEy
_ZNKSt6vectorI7Point3DSaIS0_EE14_M_range_checkEy:
.LFB3485:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	cmpq	%rax, 24(%rbp)
	setnb	%al
	testb	%al, %al
	je	.L92
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	movq	%rax, %rdx
	movq	24(%rbp), %rax
	movq	%rdx, %r8
	movq	%rax, %rdx
	leaq	.LC3(%rip), %rax
	movq	%rax, %rcx
	call	_ZSt24__throw_out_of_range_fmtPKcz
.L92:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EEixEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EEixEy
	.def	_ZNSt6vectorI7Point3DSaIS0_EEixEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EEixEy
_ZNSt6vectorI7Point3DSaIS0_EEixEy:
.LFB3486:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	(%rax), %rcx
	movq	24(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	addq	%rcx, %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEEC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEEC2Ev
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEEC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEEC2Ev
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEEC2Ev:
.LFB3585:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE10deallocateERS4_PS3_y,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE10deallocateERS4_PS3_y
	.def	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE10deallocateERS4_PS3_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE10deallocateERS4_PS3_y
_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE10deallocateERS4_PS3_y:
.LFB3587:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE10deallocateEPS3_y
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EEEvT_S5_,"x"
	.linkonce discard
	.globl	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EEEvT_S5_
	.def	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EEEvT_S5_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EEEvT_S5_
_ZSt8_DestroyIPSt6vectorI7Point3DSaIS1_EEEvT_S5_:
.LFB3588:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Destroy_auxILb0EE9__destroyIPSt6vectorI7Point3DSaIS3_EEEEvT_S7_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorI7Point3DEC2Ev,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorI7Point3DEC2Ev
	.def	_ZNSt15__new_allocatorI7Point3DEC2Ev;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorI7Point3DEC2Ev
_ZNSt15__new_allocatorI7Point3DEC2Ev:
.LFB3591:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaI7Point3DEE10deallocateERS1_PS0_y,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaI7Point3DEE10deallocateERS1_PS0_y
	.def	_ZNSt16allocator_traitsISaI7Point3DEE10deallocateERS1_PS0_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaI7Point3DEE10deallocateERS1_PS0_y
_ZNSt16allocator_traitsISaI7Point3DEE10deallocateERS1_PS0_y:
.LFB3593:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DE10deallocateEPS0_y
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt8_DestroyIP7Point3DEvT_S2_,"x"
	.linkonce discard
	.globl	_ZSt8_DestroyIP7Point3DEvT_S2_
	.def	_ZSt8_DestroyIP7Point3DEvT_S2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt8_DestroyIP7Point3DEvT_S2_
_ZSt8_DestroyIP7Point3DEvT_S2_:
.LFB3594:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Destroy_auxILb1EE9__destroyIP7Point3DEEvT_S4_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE,"x"
	.linkonce discard
	.globl	_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE
	.def	_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE
_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE:
.LFB3595:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorI7Point3DE9constructIS0_JRKS0_EEEvPT_DpOT0_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorI7Point3DE9constructIS0_JRKS0_EEEvPT_DpOT0_
	.def	_ZNSt15__new_allocatorI7Point3DE9constructIS0_JRKS0_EEEvPT_DpOT0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorI7Point3DE9constructIS0_JRKS0_EEEvPT_DpOT0_
_ZNSt15__new_allocatorI7Point3DE9constructIS0_JRKS0_EEEvPT_DpOT0_:
.LFB3596:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	40(%rbp), %rax
	movq	%rax, %rdx
	movl	$12, %ecx
	call	_ZnwyPv
	movq	%rax, %rbx
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardIRK7Point3DEOT_RNSt16remove_referenceIS3_E4typeE
	movq	(%rax), %rdx
	movq	%rdx, (%rbx)
	movl	8(%rax), %eax
	movl	%eax, 8(%rbx)
	nop
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_,"x"
	.linkonce discard
	.align 2
	.globl	_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_
	.def	_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_
_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_:
.LFB3599:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, (%rax)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorI7Point3DSaIS0_EE12_M_check_lenEyPKc,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorI7Point3DSaIS0_EE12_M_check_lenEyPKc
	.def	_ZNKSt6vectorI7Point3DSaIS0_EE12_M_check_lenEyPKc;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorI7Point3DSaIS0_EE12_M_check_lenEyPKc
_ZNKSt6vectorI7Point3DSaIS0_EE12_M_check_lenEyPKc:
.LFB3600:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$56, %rsp
	.seh_stackalloc	56
	leaq	48(%rsp), %rbp
	.seh_setframe	%rbp, 48
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	subq	%rax, %rbx
	movq	%rbx, %rdx
	movq	40(%rbp), %rax
	cmpq	%rax, %rdx
	setb	%al
	testb	%al, %al
	je	.L106
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt20__throw_length_errorPKc
.L106:
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	movq	%rax, -16(%rbp)
	leaq	40(%rbp), %rdx
	leaq	-16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt3maxIyERKT_S2_S2_
	movq	(%rax), %rax
	addq	%rbx, %rax
	movq	%rax, -8(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	cmpq	%rax, -8(%rbp)
	jb	.L107
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv
	cmpq	-8(%rbp), %rax
	jnb	.L108
.L107:
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv
	jmp	.L109
.L108:
	movq	-8(%rbp), %rax
.L109:
	addq	$56, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE5beginEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE5beginEv
	.def	_ZNSt6vectorI7Point3DSaIS0_EE5beginEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE5beginEv
_ZNSt6vectorI7Point3DSaIS0_EE5beginEv:
.LFB3601:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS2_
	movq	-8(%rbp), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZN9__gnu_cxxmiIP7Point3DSt6vectorIS1_SaIS1_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKS9_SC_,"x"
	.linkonce discard
	.globl	_ZN9__gnu_cxxmiIP7Point3DSt6vectorIS1_SaIS1_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKS9_SC_
	.def	_ZN9__gnu_cxxmiIP7Point3DSt6vectorIS1_SaIS1_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKS9_SC_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZN9__gnu_cxxmiIP7Point3DSt6vectorIS1_SaIS1_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKS9_SC_
_ZN9__gnu_cxxmiIP7Point3DSt6vectorIS1_SaIS1_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKS9_SC_:
.LFB3602:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	movq	(%rax), %rbx
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	movq	(%rax), %rax
	subq	%rax, %rbx
	movq	%rbx, %rdx
	sarq	$2, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy
_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy:
.LFB3603:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	cmpq	$0, 24(%rbp)
	je	.L116
	movq	16(%rbp), %rax
	movq	24(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaI7Point3DEE8allocateERS1_y
	jmp	.L118
.L116:
	movl	$0, %eax
.L118:
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_,"x"
	.linkonce discard
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_
	.def	_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_
_ZNSt6vectorI7Point3DSaIS0_EE11_S_relocateEPS0_S3_S3_RS1_:
.LFB3604:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	%r9, 40(%rbp)
	movq	40(%rbp), %r8
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%r8, %r9
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt12__relocate_aIP7Point3DS1_SaIS0_EET0_T_S4_S3_RT1_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	.def	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
_ZNK9__gnu_cxx17__normal_iteratorIP7Point3DSt6vectorIS1_SaIS1_EEE4baseEv:
.LFB3605:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE,"x"
	.linkonce discard
	.globl	_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE
	.def	_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE
_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE:
.LFB3607:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_:
.LFB3608:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%r12
	.seh_pushreg	%r12
	pushq	%rdi
	.seh_pushreg	%rdi
	pushq	%rsi
	.seh_pushreg	%rsi
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$32, %rsp
	.seh_stackalloc	32
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 48(%rbp)
	movq	%rdx, 56(%rbp)
	movq	%r8, 64(%rbp)
	movq	56(%rbp), %rbx
	movq	%rbx, %rdx
	movl	$24, %ecx
	call	_ZnwyPv
	movq	%rax, %rsi
	movl	$1, %r12d
	movq	64(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardIRKSt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS6_E4typeE
	movq	%rax, %rdx
	movq	%rsi, %rcx
.LEHB9:
	call	_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_
.LEHE9:
	jmp	.L129
.L128:
	movq	%rax, %rdi
	testb	%r12b, %r12b
	je	.L127
	movq	%rbx, %rdx
	movq	%rsi, %rcx
	call	_ZdlPvS_
.L127:
	movq	%rdi, %rax
	movq	%rax, %rcx
.LEHB10:
	call	_Unwind_Resume
	nop
.LEHE10:
.L129:
	addq	$32, %rsp
	popq	%rbx
	popq	%rsi
	popq	%rdi
	popq	%r12
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3608:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3608-.LLSDACSB3608
.LLSDACSB3608:
	.uleb128 .LEHB9-.LFB3608
	.uleb128 .LEHE9-.LEHB9
	.uleb128 .L128-.LFB3608
	.uleb128 0
	.uleb128 .LEHB10-.LFB3608
	.uleb128 .LEHE10-.LEHB10
	.uleb128 0
	.uleb128 0
.LLSDACSE3608:
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JRKS3_EEEvPT_DpOT0_,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_,"x"
	.linkonce discard
	.align 2
	.globl	_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_
	.def	_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_
_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_:
.LFB3611:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, (%rax)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE12_M_check_lenEyPKc,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE12_M_check_lenEyPKc
	.def	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE12_M_check_lenEyPKc;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE12_M_check_lenEyPKc
_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE12_M_check_lenEyPKc:
.LFB3612:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$56, %rsp
	.seh_stackalloc	56
	leaq	48(%rsp), %rbp
	.seh_setframe	%rbp, 48
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	subq	%rax, %rbx
	movq	%rbx, %rdx
	movq	40(%rbp), %rax
	cmpq	%rax, %rdx
	setb	%al
	testb	%al, %al
	je	.L132
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt20__throw_length_errorPKc
.L132:
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	movq	%rax, -16(%rbp)
	leaq	40(%rbp), %rdx
	leaq	-16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt3maxIyERKT_S2_S2_
	movq	(%rax), %rax
	addq	%rbx, %rax
	movq	%rax, -8(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	cmpq	%rax, -8(%rbp)
	jb	.L133
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv
	cmpq	-8(%rbp), %rax
	jnb	.L134
.L133:
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv
	jmp	.L135
.L134:
	movq	-8(%rbp), %rax
.L135:
	addq	$56, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE5beginEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE5beginEv
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE5beginEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE5beginEv
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE5beginEv:
.LFB3613:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEC1ERKS5_
	movq	-8(%rbp), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZN9__gnu_cxxmiIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKSB_SE_,"x"
	.linkonce discard
	.globl	_ZN9__gnu_cxxmiIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKSB_SE_
	.def	_ZN9__gnu_cxxmiIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKSB_SE_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZN9__gnu_cxxmiIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKSB_SE_
_ZN9__gnu_cxxmiIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEEENS_17__normal_iteratorIT_T0_E15difference_typeERKSB_SE_:
.LFB3614:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv
	movq	(%rax), %rbx
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv
	movq	(%rax), %rax
	subq	%rax, %rbx
	movq	%rbx, %rdx
	sarq	$3, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE11_M_allocateEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE11_M_allocateEy
	.def	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE11_M_allocateEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE11_M_allocateEy
_ZNSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE11_M_allocateEy:
.LFB3615:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	cmpq	$0, 24(%rbp)
	je	.L142
	movq	16(%rbp), %rax
	movq	24(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8allocateERS4_y
	jmp	.L144
.L142:
	movl	$0, %eax
.L144:
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_,"x"
	.linkonce discard
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_relocateEPS2_S5_S5_RS3_:
.LFB3616:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	%r9, 40(%rbp)
	movq	40(%rbp), %r8
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%r8, %r9
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt12__relocate_aIPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv
	.def	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv
_ZNK9__gnu_cxx17__normal_iteratorIPSt6vectorI7Point3DSaIS2_EES1_IS4_SaIS4_EEE4baseEv:
.LFB3617:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_
	.def	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_
_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_:
.LFB3618:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE7destroyIS3_EEvPT_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
	.def	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv
_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE4sizeEv:
.LFB3619:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	subq	%rax, %rdx
	sarq	$3, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE10deallocateEPS3_y,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE10deallocateEPS3_y
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE10deallocateEPS3_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE10deallocateEPS3_y
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE10deallocateEPS3_y:
.LFB3688:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$3, %rax
	movq	%rax, %rdx
	movq	24(%rbp), %rax
	movq	%rax, %rcx
	call	_ZdlPvy
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Destroy_auxILb0EE9__destroyIPSt6vectorI7Point3DSaIS3_EEEEvT_S7_,"x"
	.linkonce discard
	.globl	_ZNSt12_Destroy_auxILb0EE9__destroyIPSt6vectorI7Point3DSaIS3_EEEEvT_S7_
	.def	_ZNSt12_Destroy_auxILb0EE9__destroyIPSt6vectorI7Point3DSaIS3_EEEEvT_S7_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Destroy_auxILb0EE9__destroyIPSt6vectorI7Point3DSaIS3_EEEEvT_S7_
_ZNSt12_Destroy_auxILb0EE9__destroyIPSt6vectorI7Point3DSaIS3_EEEEvT_S7_:
.LFB3689:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	jmp	.L155
.L156:
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_
	movq	%rax, %rcx
	call	_ZSt8_DestroyISt6vectorI7Point3DSaIS1_EEEvPT_
	addq	$24, 16(%rbp)
.L155:
	movq	16(%rbp), %rax
	cmpq	24(%rbp), %rax
	jne	.L156
	nop
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorI7Point3DE10deallocateEPS0_y,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorI7Point3DE10deallocateEPS0_y
	.def	_ZNSt15__new_allocatorI7Point3DE10deallocateEPS0_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorI7Point3DE10deallocateEPS0_y
_ZNSt15__new_allocatorI7Point3DE10deallocateEPS0_y:
.LFB3690:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rdx
	movq	24(%rbp), %rax
	movq	%rax, %rcx
	call	_ZdlPvy
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Destroy_auxILb1EE9__destroyIP7Point3DEEvT_S4_,"x"
	.linkonce discard
	.globl	_ZNSt12_Destroy_auxILb1EE9__destroyIP7Point3DEEvT_S4_
	.def	_ZNSt12_Destroy_auxILb1EE9__destroyIP7Point3DEEvT_S4_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Destroy_auxILb1EE9__destroyIP7Point3DEEvT_S4_
_ZNSt12_Destroy_auxILb1EE9__destroyIP7Point3DEEvT_S4_:
.LFB3691:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv
	.def	_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv
_ZNKSt6vectorI7Point3DSaIS0_EE8max_sizeEv:
.LFB3692:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EE11_S_max_sizeERKS1_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt3maxIyERKT_S2_S2_,"x"
	.linkonce discard
	.globl	_ZSt3maxIyERKT_S2_S2_
	.def	_ZSt3maxIyERKT_S2_S2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt3maxIyERKT_S2_S2_
_ZSt3maxIyERKT_S2_S2_:
.LFB3693:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	(%rax), %rdx
	movq	24(%rbp), %rax
	movq	(%rax), %rax
	cmpq	%rax, %rdx
	jnb	.L163
	movq	24(%rbp), %rax
	jmp	.L164
.L163:
	movq	16(%rbp), %rax
.L164:
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaI7Point3DEE8allocateERS1_y,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaI7Point3DEE8allocateERS1_y
	.def	_ZNSt16allocator_traitsISaI7Point3DEE8allocateERS1_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaI7Point3DEE8allocateERS1_y
_ZNSt16allocator_traitsISaI7Point3DEE8allocateERS1_y:
.LFB3694:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movl	$0, %r8d
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DE8allocateEyPKv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__relocate_aIP7Point3DS1_SaIS0_EET0_T_S4_S3_RT1_,"x"
	.linkonce discard
	.globl	_ZSt12__relocate_aIP7Point3DS1_SaIS0_EET0_T_S4_S3_RT1_
	.def	_ZSt12__relocate_aIP7Point3DS1_SaIS0_EET0_T_S4_S3_RT1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__relocate_aIP7Point3DS1_SaIS0_EET0_T_S4_S3_RT1_
_ZSt12__relocate_aIP7Point3DS1_SaIS0_EET0_T_S4_S3_RT1_:
.LFB3695:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rsi
	.seh_pushreg	%rsi
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$32, %rsp
	.seh_stackalloc	32
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	%r9, 56(%rbp)
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIP7Point3DET_S2_
	movq	%rax, %rsi
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIP7Point3DET_S2_
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIP7Point3DET_S2_
	movq	56(%rbp), %rdx
	movq	%rdx, %r9
	movq	%rsi, %r8
	movq	%rbx, %rdx
	movq	%rax, %rcx
	call	_ZSt14__relocate_a_1I7Point3DS0_ENSt9enable_ifIXsrSt24__is_bitwise_relocatableIT_vE5valueEPS3_E4typeES5_S5_S5_RSaIT0_E
	addq	$32, %rsp
	popq	%rbx
	popq	%rsi
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_
	.def	_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_
_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_:
.LFB3699:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rdi
	.seh_pushreg	%rdi
	pushq	%rsi
	.seh_pushreg	%rsi
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$56, %rsp
	.seh_stackalloc	56
	leaq	48(%rsp), %rbp
	.seh_setframe	%rbp, 48
	.seh_endprologue
	movq	%rcx, 48(%rbp)
	movq	%rdx, 56(%rbp)
	movq	48(%rbp), %rbx
	movq	56(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rdx
	leaq	-1(%rbp), %rax
	movq	%rax, %rcx
.LEHB11:
	call	_ZN9__gnu_cxx14__alloc_traitsISaI7Point3DES1_E17_S_select_on_copyERKS2_
.LEHE11:
	movq	56(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE4sizeEv
	leaq	-1(%rbp), %rdx
	movq	%rdx, %r8
	movq	%rax, %rdx
	movq	%rbx, %rcx
.LEHB12:
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_
.LEHE12:
	leaq	-1(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DED1Ev
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rsi
	movq	48(%rbp), %rax
	movq	(%rax), %rdi
	movq	56(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE3endEv
	movq	%rax, %rbx
	movq	56(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt6vectorI7Point3DSaIS0_EE5beginEv
	movq	%rsi, %r9
	movq	%rdi, %r8
	movq	%rbx, %rdx
	movq	%rax, %rcx
.LEHB13:
	call	_ZSt22__uninitialized_copy_aIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_S2_ET0_T_SB_SA_RSaIT1_E
.LEHE13:
	movq	48(%rbp), %rdx
	movq	%rax, 8(%rdx)
	jmp	.L174
.L172:
	movq	%rax, %rbx
	leaq	-1(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DED1Ev
	movq	%rbx, %rax
	movq	%rax, %rcx
.LEHB14:
	call	_Unwind_Resume
.L173:
	movq	%rax, %rbx
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EED2Ev
	movq	%rbx, %rax
	movq	%rax, %rcx
	call	_Unwind_Resume
	nop
.LEHE14:
.L174:
	addq	$56, %rsp
	popq	%rbx
	popq	%rsi
	popq	%rdi
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3699:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3699-.LLSDACSB3699
.LLSDACSB3699:
	.uleb128 .LEHB11-.LFB3699
	.uleb128 .LEHE11-.LEHB11
	.uleb128 0
	.uleb128 0
	.uleb128 .LEHB12-.LFB3699
	.uleb128 .LEHE12-.LEHB12
	.uleb128 .L172-.LFB3699
	.uleb128 0
	.uleb128 .LEHB13-.LFB3699
	.uleb128 .LEHE13-.LEHB13
	.uleb128 .L173-.LFB3699
	.uleb128 0
	.uleb128 .LEHB14-.LFB3699
	.uleb128 .LEHE14-.LEHB14
	.uleb128 0
	.uleb128 0
.LLSDACSE3699:
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EEC1ERKS2_,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv
	.def	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv
_ZNKSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE8max_sizeEv:
.LFB3700:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	movq	%rax, %rcx
	call	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_max_sizeERKS3_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8allocateERS4_y,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8allocateERS4_y
	.def	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8allocateERS4_y;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8allocateERS4_y
_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8allocateERS4_y:
.LFB3701:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movl	$0, %r8d
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8allocateEyPKv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__relocate_aIPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_,"x"
	.linkonce discard
	.globl	_ZSt12__relocate_aIPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_
	.def	_ZSt12__relocate_aIPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__relocate_aIPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_
_ZSt12__relocate_aIPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_:
.LFB3702:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rsi
	.seh_pushreg	%rsi
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$32, %rsp
	.seh_stackalloc	32
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	%r9, 56(%rbp)
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_
	movq	%rax, %rsi
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_
	movq	56(%rbp), %rdx
	movq	%rdx, %r9
	movq	%rsi, %r8
	movq	%rbx, %rdx
	movq	%rax, %rcx
	call	_ZSt14__relocate_a_1IPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_
	addq	$32, %rsp
	popq	%rbx
	popq	%rsi
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE7destroyIS3_EEvPT_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE7destroyIS3_EEvPT_
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE7destroyIS3_EEvPT_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE7destroyIS3_EEvPT_
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE7destroyIS3_EEvPT_:
.LFB3703:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EED1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_,"x"
	.linkonce discard
	.globl	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_
	.def	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_
_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_:
.LFB3729:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt8_DestroyISt6vectorI7Point3DSaIS1_EEEvPT_,"x"
	.linkonce discard
	.globl	_ZSt8_DestroyISt6vectorI7Point3DSaIS1_EEEvPT_
	.def	_ZSt8_DestroyISt6vectorI7Point3DSaIS1_EEEvPT_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt8_DestroyISt6vectorI7Point3DSaIS1_EEEvPT_
_ZSt8_DestroyISt6vectorI7Point3DSaIS1_EEEvPT_:
.LFB3730:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EED1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EE11_S_max_sizeERKS1_,"x"
	.linkonce discard
	.globl	_ZNSt6vectorI7Point3DSaIS0_EE11_S_max_sizeERKS1_
	.def	_ZNSt6vectorI7Point3DSaIS0_EE11_S_max_sizeERKS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EE11_S_max_sizeERKS1_
_ZNSt6vectorI7Point3DSaIS0_EE11_S_max_sizeERKS1_:
.LFB3731:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movabsq	$768614336404564650, %rax
	movq	%rax, -8(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaI7Point3DEE8max_sizeERKS1_
	movq	%rax, -16(%rbp)
	leaq	-16(%rbp), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt3minIyERKT_S2_S2_
	movq	(%rax), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
	.def	_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv
_ZNKSt12_Vector_baseI7Point3DSaIS0_EE19_M_get_Tp_allocatorEv:
.LFB3732:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorI7Point3DE8allocateEyPKv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorI7Point3DE8allocateEyPKv
	.def	_ZNSt15__new_allocatorI7Point3DE8allocateEyPKv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorI7Point3DE8allocateEyPKv
_ZNSt15__new_allocatorI7Point3DE8allocateEyPKv:
.LFB3733:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv
	cmpq	24(%rbp), %rax
	setb	%al
	movzbl	%al, %eax
	testl	%eax, %eax
	setne	%al
	testb	%al, %al
	je	.L190
	movabsq	$1537228672809129301, %rax
	cmpq	24(%rbp), %rax
	jnb	.L191
	call	_ZSt28__throw_bad_array_new_lengthv
.L191:
	call	_ZSt17__throw_bad_allocv
.L190:
	movq	24(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rcx
	call	_Znwy
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__niter_baseIP7Point3DET_S2_,"x"
	.linkonce discard
	.globl	_ZSt12__niter_baseIP7Point3DET_S2_
	.def	_ZSt12__niter_baseIP7Point3DET_S2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__niter_baseIP7Point3DET_S2_
_ZSt12__niter_baseIP7Point3DET_S2_:
.LFB3734:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt14__relocate_a_1I7Point3DS0_ENSt9enable_ifIXsrSt24__is_bitwise_relocatableIT_vE5valueEPS3_E4typeES5_S5_S5_RSaIT0_E,"x"
	.linkonce discard
	.globl	_ZSt14__relocate_a_1I7Point3DS0_ENSt9enable_ifIXsrSt24__is_bitwise_relocatableIT_vE5valueEPS3_E4typeES5_S5_S5_RSaIT0_E
	.def	_ZSt14__relocate_a_1I7Point3DS0_ENSt9enable_ifIXsrSt24__is_bitwise_relocatableIT_vE5valueEPS3_E4typeES5_S5_S5_RSaIT0_E;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt14__relocate_a_1I7Point3DS0_ENSt9enable_ifIXsrSt24__is_bitwise_relocatableIT_vE5valueEPS3_E4typeES5_S5_S5_RSaIT0_E
_ZSt14__relocate_a_1I7Point3DS0_ENSt9enable_ifIXsrSt24__is_bitwise_relocatableIT_vE5valueEPS3_E4typeES5_S5_S5_RSaIT0_E:
.LFB3735:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	%r9, 40(%rbp)
	movq	24(%rbp), %rax
	subq	16(%rbp), %rax
	sarq	$2, %rax
	movq	%rax, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	movq	%rax, -8(%rbp)
	cmpq	$0, -8(%rbp)
	jle	.L196
	movq	-8(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rcx
	movq	16(%rbp), %rdx
	movq	32(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	memmove
.L196:
	movq	-8(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rdx
	movq	32(%rbp), %rax
	addq	%rdx, %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZN9__gnu_cxx14__alloc_traitsISaI7Point3DES1_E17_S_select_on_copyERKS2_,"x"
	.linkonce discard
	.globl	_ZN9__gnu_cxx14__alloc_traitsISaI7Point3DES1_E17_S_select_on_copyERKS2_
	.def	_ZN9__gnu_cxx14__alloc_traitsISaI7Point3DES1_E17_S_select_on_copyERKS2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZN9__gnu_cxx14__alloc_traitsISaI7Point3DES1_E17_S_select_on_copyERKS2_
_ZN9__gnu_cxx14__alloc_traitsISaI7Point3DES1_E17_S_select_on_copyERKS2_:
.LFB3736:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	24(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaI7Point3DEE37select_on_container_copy_constructionERKS1_
	movq	16(%rbp), %rax
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_
_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_:
.LFB3738:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	32(%rbp), %rax
	movq	48(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1ERKS1_
	movq	40(%rbp), %rdx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
.LEHB15:
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_M_create_storageEy
.LEHE15:
	jmp	.L203
.L202:
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implD1Ev
	movq	%rbx, %rax
	movq	%rax, %rcx
.LEHB16:
	call	_Unwind_Resume
	nop
.LEHE16:
.L203:
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_handler	__gxx_personality_seh0, @unwind, @except
	.seh_handlerdata
.LLSDA3738:
	.byte	0xff
	.byte	0xff
	.byte	0x1
	.uleb128 .LLSDACSE3738-.LLSDACSB3738
.LLSDACSB3738:
	.uleb128 .LEHB15-.LFB3738
	.uleb128 .LEHE15-.LEHB15
	.uleb128 .L202-.LFB3738
	.uleb128 0
	.uleb128 .LEHB16-.LFB3738
	.uleb128 .LEHE16-.LEHB16
	.uleb128 0
	.uleb128 0
.LLSDACSE3738:
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EyRKS1_,"x"
	.linkonce discard
	.seh_endproc
	.section	.text$_ZNKSt6vectorI7Point3DSaIS0_EE5beginEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorI7Point3DSaIS0_EE5beginEv
	.def	_ZNKSt6vectorI7Point3DSaIS0_EE5beginEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorI7Point3DSaIS0_EE5beginEv
_ZNKSt6vectorI7Point3DSaIS0_EE5beginEv:
.LFB3740:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_
	movq	-8(%rbp), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt6vectorI7Point3DSaIS0_EE3endEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt6vectorI7Point3DSaIS0_EE3endEv
	.def	_ZNKSt6vectorI7Point3DSaIS0_EE3endEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt6vectorI7Point3DSaIS0_EE3endEv
_ZNKSt6vectorI7Point3DSaIS0_EE3endEv:
.LFB3741:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	leaq	8(%rax), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_
	movq	-8(%rbp), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt22__uninitialized_copy_aIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_S2_ET0_T_SB_SA_RSaIT1_E,"x"
	.linkonce discard
	.globl	_ZSt22__uninitialized_copy_aIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_S2_ET0_T_SB_SA_RSaIT1_E
	.def	_ZSt22__uninitialized_copy_aIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_S2_ET0_T_SB_SA_RSaIT1_E;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt22__uninitialized_copy_aIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_S2_ET0_T_SB_SA_RSaIT1_E
_ZSt22__uninitialized_copy_aIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_S2_ET0_T_SB_SA_RSaIT1_E:
.LFB3742:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	%r9, 40(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt18uninitialized_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_max_sizeERKS3_,"x"
	.linkonce discard
	.globl	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_max_sizeERKS3_
	.def	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_max_sizeERKS3_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_max_sizeERKS3_
_ZNSt6vectorIS_I7Point3DSaIS0_EESaIS2_EE11_S_max_sizeERKS3_:
.LFB3743:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movabsq	$384307168202282325, %rax
	movq	%rax, -8(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8max_sizeERKS4_
	movq	%rax, -16(%rbp)
	leaq	-16(%rbp), %rdx
	leaq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt3minIyERKT_S2_S2_
	movq	(%rax), %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
	.def	_ZNKSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv
_ZNKSt12_Vector_baseISt6vectorI7Point3DSaIS1_EESaIS3_EE19_M_get_Tp_allocatorEv:
.LFB3744:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8allocateEyPKv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8allocateEyPKv
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8allocateEyPKv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8allocateEyPKv
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8allocateEyPKv:
.LFB3745:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv
	cmpq	24(%rbp), %rax
	setb	%al
	movzbl	%al, %eax
	testl	%eax, %eax
	setne	%al
	testb	%al, %al
	je	.L215
	movabsq	$768614336404564650, %rax
	cmpq	24(%rbp), %rax
	jnb	.L216
	call	_ZSt28__throw_bad_array_new_lengthv
.L216:
	call	_ZSt17__throw_bad_allocv
.L215:
	movq	24(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$3, %rax
	movq	%rax, %rcx
	call	_Znwy
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_,"x"
	.linkonce discard
	.globl	_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_
	.def	_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_
_ZSt12__niter_baseIPSt6vectorI7Point3DSaIS1_EEET_S5_:
.LFB3746:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt14__relocate_a_1IPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_,"x"
	.linkonce discard
	.globl	_ZSt14__relocate_a_1IPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_
	.def	_ZSt14__relocate_a_1IPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt14__relocate_a_1IPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_
_ZSt14__relocate_a_1IPSt6vectorI7Point3DSaIS1_EES4_SaIS3_EET0_T_S7_S6_RT1_:
.LFB3747:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$56, %rsp
	.seh_stackalloc	56
	leaq	48(%rsp), %rbp
	.seh_setframe	%rbp, 48
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	%r9, 56(%rbp)
	movq	48(%rbp), %rax
	movq	%rax, -8(%rbp)
	jmp	.L221
.L222:
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_
	movq	%rax, %rbx
	movq	-8(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_
	movq	56(%rbp), %rdx
	movq	%rdx, %r8
	movq	%rbx, %rdx
	movq	%rax, %rcx
	call	_ZSt19__relocate_object_aISt6vectorI7Point3DSaIS1_EES3_SaIS3_EEvPT_PT0_RT1_
	addq	$24, 32(%rbp)
	addq	$24, -8(%rbp)
.L221:
	movq	32(%rbp), %rax
	cmpq	40(%rbp), %rax
	jne	.L222
	movq	-8(%rbp), %rax
	addq	$56, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaI7Point3DEE8max_sizeERKS1_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaI7Point3DEE8max_sizeERKS1_
	.def	_ZNSt16allocator_traitsISaI7Point3DEE8max_sizeERKS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaI7Point3DEE8max_sizeERKS1_
_ZNSt16allocator_traitsISaI7Point3DEE8max_sizeERKS1_:
.LFB3759:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt15__new_allocatorI7Point3DE8max_sizeEv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt3minIyERKT_S2_S2_,"x"
	.linkonce discard
	.globl	_ZSt3minIyERKT_S2_S2_
	.def	_ZSt3minIyERKT_S2_S2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt3minIyERKT_S2_S2_
_ZSt3minIyERKT_S2_S2_:
.LFB3760:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	(%rax), %rax
	cmpq	%rax, %rdx
	jnb	.L227
	movq	24(%rbp), %rax
	jmp	.L228
.L227:
	movq	16(%rbp), %rax
.L228:
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv
	.def	_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv
_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv:
.LFB3761:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movabsq	$768614336404564650, %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaI7Point3DEE37select_on_container_copy_constructionERKS1_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaI7Point3DEE37select_on_container_copy_constructionERKS1_
	.def	_ZNSt16allocator_traitsISaI7Point3DEE37select_on_container_copy_constructionERKS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaI7Point3DEE37select_on_container_copy_constructionERKS1_
_ZNSt16allocator_traitsISaI7Point3DEE37select_on_container_copy_constructionERKS1_:
.LFB3762:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DEC1ERKS0_
	movq	16(%rbp), %rax
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1ERKS1_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1ERKS1_
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1ERKS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1ERKS1_
_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1ERKS1_:
.LFB3765:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DEC2ERKS0_
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_M_create_storageEy,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_M_create_storageEy
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_M_create_storageEy;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_M_create_storageEy
_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_M_create_storageEy:
.LFB3766:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE11_M_allocateEy
	movq	16(%rbp), %rdx
	movq	%rax, (%rdx)
	movq	16(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, 8(%rax)
	movq	16(%rbp), %rax
	movq	(%rax), %rcx
	movq	24(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	leaq	(%rcx,%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, 16(%rax)
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_,"x"
	.linkonce discard
	.align 2
	.globl	_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_
	.def	_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_
_ZN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEEC1ERKS3_:
.LFB3769:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, (%rax)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt18uninitialized_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_,"x"
	.linkonce discard
	.globl	_ZSt18uninitialized_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_
	.def	_ZSt18uninitialized_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt18uninitialized_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_
_ZSt18uninitialized_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_:
.LFB3770:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movb	$1, -1(%rbp)
	movb	$1, -2(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt20__uninitialized_copyILb1EE13__uninit_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS4_SaIS4_EEEEPS4_EET0_T_SD_SC_
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8max_sizeERKS4_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8max_sizeERKS4_
	.def	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8max_sizeERKS4_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8max_sizeERKS4_
_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE8max_sizeERKS4_:
.LFB3772:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8max_sizeEv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv
	.def	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv
_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv:
.LFB3773:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movabsq	$384307168202282325, %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt19__relocate_object_aISt6vectorI7Point3DSaIS1_EES3_SaIS3_EEvPT_PT0_RT1_,"x"
	.linkonce discard
	.globl	_ZSt19__relocate_object_aISt6vectorI7Point3DSaIS1_EES3_SaIS3_EEvPT_PT0_RT1_
	.def	_ZSt19__relocate_object_aISt6vectorI7Point3DSaIS1_EES3_SaIS3_EEvPT_PT0_RT1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt19__relocate_object_aISt6vectorI7Point3DSaIS1_EES3_SaIS3_EEvPT_PT0_RT1_
_ZSt19__relocate_object_aISt6vectorI7Point3DSaIS1_EES3_SaIS3_EEvPT_PT0_RT1_:
.LFB3774:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	24(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt4moveIRSt6vectorI7Point3DSaIS1_EEEONSt16remove_referenceIT_E4typeEOS6_
	movq	%rax, %rcx
	movq	16(%rbp), %rdx
	movq	32(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JS3_EEEvRS4_PT_DpOT0_
	movq	24(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt11__addressofISt6vectorI7Point3DSaIS1_EEEPT_RS4_
	movq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE7destroyIS3_EEvRS4_PT_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt15__new_allocatorI7Point3DE8max_sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt15__new_allocatorI7Point3DE8max_sizeEv
	.def	_ZNKSt15__new_allocatorI7Point3DE8max_sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt15__new_allocatorI7Point3DE8max_sizeEv
_ZNKSt15__new_allocatorI7Point3DE8max_sizeEv:
.LFB3779:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt15__new_allocatorI7Point3DE11_M_max_sizeEv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaI7Point3DEC2ERKS0_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaI7Point3DEC2ERKS0_
	.def	_ZNSaI7Point3DEC2ERKS0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaI7Point3DEC2ERKS0_
_ZNSaI7Point3DEC2ERKS0_:
.LFB3781:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DEC2ERKS1_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSaI7Point3DEC1ERKS0_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSaI7Point3DEC1ERKS0_
	.def	_ZNSaI7Point3DEC1ERKS0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSaI7Point3DEC1ERKS0_
_ZNSaI7Point3DEC1ERKS0_:
.LFB3782:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorI7Point3DEC2ERKS1_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt20__uninitialized_copyILb1EE13__uninit_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS4_SaIS4_EEEEPS4_EET0_T_SD_SC_,"x"
	.linkonce discard
	.globl	_ZNSt20__uninitialized_copyILb1EE13__uninit_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS4_SaIS4_EEEEPS4_EET0_T_SD_SC_
	.def	_ZNSt20__uninitialized_copyILb1EE13__uninit_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS4_SaIS4_EEEEPS4_EET0_T_SD_SC_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt20__uninitialized_copyILb1EE13__uninit_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS4_SaIS4_EEEEPS4_EET0_T_SD_SC_
_ZNSt20__uninitialized_copyILb1EE13__uninit_copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS4_SaIS4_EEEEPS4_EET0_T_SD_SC_:
.LFB3783:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt4copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8max_sizeEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8max_sizeEv
	.def	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8max_sizeEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8max_sizeEv
_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE8max_sizeEv:
.LFB3784:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNKSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE11_M_max_sizeEv
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt4moveIRSt6vectorI7Point3DSaIS1_EEEONSt16remove_referenceIT_E4typeEOS6_,"x"
	.linkonce discard
	.globl	_ZSt4moveIRSt6vectorI7Point3DSaIS1_EEEONSt16remove_referenceIT_E4typeEOS6_
	.def	_ZSt4moveIRSt6vectorI7Point3DSaIS1_EEEONSt16remove_referenceIT_E4typeEOS6_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt4moveIRSt6vectorI7Point3DSaIS1_EEEONSt16remove_referenceIT_E4typeEOS6_
_ZSt4moveIRSt6vectorI7Point3DSaIS1_EEEONSt16remove_referenceIT_E4typeEOS6_:
.LFB3785:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JS3_EEEvRS4_PT_DpOT0_,"x"
	.linkonce discard
	.globl	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JS3_EEEvRS4_PT_DpOT0_
	.def	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JS3_EEEvRS4_PT_DpOT0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JS3_EEEvRS4_PT_DpOT0_
_ZNSt16allocator_traitsISaISt6vectorI7Point3DSaIS1_EEEE9constructIS3_JS3_EEEvRS4_PT_DpOT0_:
.LFB3786:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE
	movq	%rax, %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JS3_EEEvPT_DpOT0_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorI7Point3DEC2ERKS1_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorI7Point3DEC2ERKS1_
	.def	_ZNSt15__new_allocatorI7Point3DEC2ERKS1_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorI7Point3DEC2ERKS1_
_ZNSt15__new_allocatorI7Point3DEC2ERKS1_:
.LFB3788:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt4copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_,"x"
	.linkonce discard
	.globl	_ZSt4copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_
	.def	_ZSt4copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt4copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_
_ZSt4copyIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET0_T_SB_SA_:
.LFB3790:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_
	movq	48(%rbp), %rdx
	movq	%rdx, %r8
	movq	%rbx, %rdx
	movq	%rax, %rcx
	call	_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET1_T0_SB_SA_
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE,"x"
	.linkonce discard
	.globl	_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE
	.def	_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE
_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE:
.LFB3791:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EOS2_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EOS2_
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EOS2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EOS2_
_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EOS2_:
.LFB3795:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	24(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1EOS3_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt6vectorI7Point3DSaIS0_EEC1EOS2_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt6vectorI7Point3DSaIS0_EEC1EOS2_
	.def	_ZNSt6vectorI7Point3DSaIS0_EEC1EOS2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt6vectorI7Point3DSaIS0_EEC1EOS2_
_ZNSt6vectorI7Point3DSaIS0_EEC1EOS2_:
.LFB3798:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	16(%rbp), %rax
	movq	24(%rbp), %rdx
	movq	%rax, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EEC2EOS2_
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JS3_EEEvPT_DpOT0_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JS3_EEEvPT_DpOT0_
	.def	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JS3_EEEvPT_DpOT0_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JS3_EEEvPT_DpOT0_
_ZNSt15__new_allocatorISt6vectorI7Point3DSaIS1_EEE9constructIS3_JS3_EEEvPT_DpOT0_:
.LFB3792:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	40(%rbp), %rax
	movq	%rax, %rdx
	movl	$24, %ecx
	call	_ZnwyPv
	movq	%rax, %rbx
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt7forwardISt6vectorI7Point3DSaIS1_EEEOT_RNSt16remove_referenceIS4_E4typeE
	movq	%rax, %rdx
	movq	%rbx, %rcx
	call	_ZNSt6vectorI7Point3DSaIS0_EEC1EOS2_
	nop
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_,"x"
	.linkonce discard
	.globl	_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_
	.def	_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_
_ZSt12__miter_baseIN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEET_S9_:
.LFB3799:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET1_T0_SB_SA_,"x"
	.linkonce discard
	.globl	_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET1_T0_SB_SA_
	.def	_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET1_T0_SB_SA_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET1_T0_SB_SA_
_ZSt13__copy_move_aILb0EN9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS2_SaIS2_EEEEPS2_ET1_T0_SB_SA_:
.LFB3800:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rsi
	.seh_pushreg	%rsi
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$32, %rsp
	.seh_stackalloc	32
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	%r8, 48(%rbp)
	movq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIP7Point3DET_S2_
	movq	%rax, %rsi
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE
	movq	%rax, %rbx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE
	movq	%rsi, %r8
	movq	%rbx, %rdx
	movq	%rax, %rcx
	call	_ZSt14__copy_move_a1ILb0EPK7Point3DPS0_ET1_T0_S5_S4_
	movq	%rax, %rdx
	leaq	48(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt12__niter_wrapIP7Point3DET_RKS2_S2_
	addq	$32, %rsp
	popq	%rbx
	popq	%rsi
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1EOS3_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1EOS3_
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1EOS3_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1EOS3_
_ZNSt12_Vector_baseI7Point3DSaIS0_EE12_Vector_implC1EOS3_:
.LFB3804:
	pushq	%rbp
	.seh_pushreg	%rbp
	pushq	%rbx
	.seh_pushreg	%rbx
	subq	$40, %rsp
	.seh_stackalloc	40
	leaq	32(%rsp), %rbp
	.seh_setframe	%rbp, 32
	.seh_endprologue
	movq	%rcx, 32(%rbp)
	movq	%rdx, 40(%rbp)
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_
	movq	%rax, %rdx
	movq	32(%rbp), %rax
	movq	%rax, %rcx
	call	_ZNSaI7Point3DEC2ERKS0_
	movq	32(%rbp), %rbx
	movq	40(%rbp), %rax
	movq	%rax, %rcx
	call	_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_
	movq	%rax, %rdx
	movq	%rbx, %rcx
	call	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2EOS3_
	nop
	addq	$40, %rsp
	popq	%rbx
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE,"x"
	.linkonce discard
	.globl	_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE
	.def	_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE
_ZSt12__niter_baseIPK7Point3DSt6vectorIS0_SaIS0_EEET_N9__gnu_cxx17__normal_iteratorIS6_T0_EE:
.LFB3805:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	leaq	16(%rbp), %rcx
	call	_ZNK9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	movq	(%rax), %rax
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt14__copy_move_a1ILb0EPK7Point3DPS0_ET1_T0_S5_S4_,"x"
	.linkonce discard
	.globl	_ZSt14__copy_move_a1ILb0EPK7Point3DPS0_ET1_T0_S5_S4_
	.def	_ZSt14__copy_move_a1ILb0EPK7Point3DPS0_ET1_T0_S5_S4_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt14__copy_move_a1ILb0EPK7Point3DPS0_ET1_T0_S5_S4_
_ZSt14__copy_move_a1ILb0EPK7Point3DPS0_ET1_T0_S5_S4_:
.LFB3806:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZSt14__copy_move_a2ILb0EPK7Point3DPS0_ET1_T0_S5_S4_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt12__niter_wrapIP7Point3DET_RKS2_S2_,"x"
	.linkonce discard
	.globl	_ZSt12__niter_wrapIP7Point3DET_RKS2_S2_
	.def	_ZSt12__niter_wrapIP7Point3DET_RKS2_S2_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt12__niter_wrapIP7Point3DET_RKS2_S2_
_ZSt12__niter_wrapIP7Point3DET_RKS2_S2_:
.LFB3807:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_,"x"
	.linkonce discard
	.globl	_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_
	.def	_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_
_ZSt4moveIRNSt12_Vector_baseI7Point3DSaIS1_EE12_Vector_implEEONSt16remove_referenceIT_E4typeEOS7_:
.LFB3808:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2EOS3_,"x"
	.linkonce discard
	.align 2
	.globl	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2EOS3_
	.def	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2EOS3_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2EOS3_
_ZNSt12_Vector_baseI7Point3DSaIS0_EE17_Vector_impl_dataC2EOS3_:
.LFB3810:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	24(%rbp), %rax
	movq	(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, (%rax)
	movq	24(%rbp), %rax
	movq	8(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, 8(%rax)
	movq	24(%rbp), %rax
	movq	16(%rax), %rdx
	movq	16(%rbp), %rax
	movq	%rdx, 16(%rax)
	movq	24(%rbp), %rax
	movq	$0, 16(%rax)
	movq	24(%rbp), %rax
	movq	16(%rax), %rdx
	movq	24(%rbp), %rax
	movq	%rdx, 8(%rax)
	movq	24(%rbp), %rax
	movq	8(%rax), %rdx
	movq	24(%rbp), %rax
	movq	%rdx, (%rax)
	nop
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNK9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEE4baseEv,"x"
	.linkonce discard
	.align 2
	.globl	_ZNK9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
	.def	_ZNK9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEE4baseEv;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNK9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEE4baseEv
_ZNK9__gnu_cxx17__normal_iteratorIPK7Point3DSt6vectorIS1_SaIS1_EEE4baseEv:
.LFB3812:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	16(%rbp), %rax
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZSt14__copy_move_a2ILb0EPK7Point3DPS0_ET1_T0_S5_S4_,"x"
	.linkonce discard
	.globl	_ZSt14__copy_move_a2ILb0EPK7Point3DPS0_ET1_T0_S5_S4_
	.def	_ZSt14__copy_move_a2ILb0EPK7Point3DPS0_ET1_T0_S5_S4_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZSt14__copy_move_a2ILb0EPK7Point3DPS0_ET1_T0_S5_S4_
_ZSt14__copy_move_a2ILb0EPK7Point3DPS0_ET1_T0_S5_S4_:
.LFB3813:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	32(%rbp), %rcx
	movq	24(%rbp), %rdx
	movq	16(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	_ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mI7Point3DEEPT_PKS4_S7_S5_
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.text$_ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mI7Point3DEEPT_PKS4_S7_S5_,"x"
	.linkonce discard
	.globl	_ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mI7Point3DEEPT_PKS4_S7_S5_
	.def	_ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mI7Point3DEEPT_PKS4_S7_S5_;	.scl	2;	.type	32;	.endef
	.seh_proc	_ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mI7Point3DEEPT_PKS4_S7_S5_
_ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mI7Point3DEEPT_PKS4_S7_S5_:
.LFB3814:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$48, %rsp
	.seh_stackalloc	48
	.seh_endprologue
	movq	%rcx, 16(%rbp)
	movq	%rdx, 24(%rbp)
	movq	%r8, 32(%rbp)
	movq	24(%rbp), %rax
	subq	16(%rbp), %rax
	sarq	$2, %rax
	movq	%rax, %rdx
	movabsq	$-6148914691236517205, %rax
	imulq	%rdx, %rax
	movq	%rax, -8(%rbp)
	cmpq	$0, -8(%rbp)
	je	.L281
	movq	-8(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rcx
	movq	16(%rbp), %rdx
	movq	32(%rbp), %rax
	movq	%rcx, %r8
	movq	%rax, %rcx
	call	memmove
.L281:
	movq	-8(%rbp), %rdx
	movq	%rdx, %rax
	addq	%rax, %rax
	addq	%rdx, %rax
	salq	$2, %rax
	movq	%rax, %rdx
	movq	32(%rbp), %rax
	addq	%rdx, %rax
	addq	$48, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.text
	.def	__tcf_0;	.scl	3;	.type	32;	.endef
	.seh_proc	__tcf_0
__tcf_0:
.LFB3816:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	leaq	_ZStL8__ioinit(%rip), %rax
	movq	%rax, %rcx
	call	_ZNSt8ios_base4InitD1Ev
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.def	_Z41__static_initialization_and_destruction_0ii;	.scl	3;	.type	32;	.endef
	.seh_proc	_Z41__static_initialization_and_destruction_0ii
_Z41__static_initialization_and_destruction_0ii:
.LFB3815:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movl	%ecx, 16(%rbp)
	movl	%edx, 24(%rbp)
	cmpl	$1, 16(%rbp)
	jne	.L286
	cmpl	$65535, 24(%rbp)
	jne	.L286
	leaq	_ZStL8__ioinit(%rip), %rax
	movq	%rax, %rcx
	call	_ZNSt8ios_base4InitC1Ev
	leaq	__tcf_0(%rip), %rax
	movq	%rax, %rcx
	call	atexit
.L286:
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.def	_GLOBAL__sub_I_main;	.scl	3;	.type	32;	.endef
	.seh_proc	_GLOBAL__sub_I_main
_GLOBAL__sub_I_main:
.LFB3817:
	pushq	%rbp
	.seh_pushreg	%rbp
	movq	%rsp, %rbp
	.seh_setframe	%rbp, 0
	subq	$32, %rsp
	.seh_stackalloc	32
	.seh_endprologue
	movl	$65535, %edx
	movl	$1, %ecx
	call	_Z41__static_initialization_and_destruction_0ii
	nop
	addq	$32, %rsp
	popq	%rbp
	ret
	.seh_endproc
	.section	.ctors,"w"
	.align 8
	.quad	_GLOBAL__sub_I_main
	.ident	"GCC: (MinGW-W64 x86_64-ucrt-posix-seh, built by Brecht Sanders) 12.2.0"
	.def	_ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc;	.scl	2;	.type	32;	.endef
	.def	_ZNSirsERi;	.scl	2;	.type	32;	.endef
	.def	_ZNSolsEi;	.scl	2;	.type	32;	.endef
	.def	_Unwind_Resume;	.scl	2;	.type	32;	.endef
	.def	__cxa_begin_catch;	.scl	2;	.type	32;	.endef
	.def	__cxa_rethrow;	.scl	2;	.type	32;	.endef
	.def	__cxa_end_catch;	.scl	2;	.type	32;	.endef
	.def	_ZSt24__throw_out_of_range_fmtPKcz;	.scl	2;	.type	32;	.endef
	.def	_ZSt20__throw_length_errorPKc;	.scl	2;	.type	32;	.endef
	.def	_ZdlPvy;	.scl	2;	.type	32;	.endef
	.def	_ZSt28__throw_bad_array_new_lengthv;	.scl	2;	.type	32;	.endef
	.def	_ZSt17__throw_bad_allocv;	.scl	2;	.type	32;	.endef
	.def	_Znwy;	.scl	2;	.type	32;	.endef
	.def	memmove;	.scl	2;	.type	32;	.endef
	.def	_ZNSt8ios_base4InitD1Ev;	.scl	2;	.type	32;	.endef
	.def	_ZNSt8ios_base4InitC1Ev;	.scl	2;	.type	32;	.endef
	.def	atexit;	.scl	2;	.type	32;	.endef
	.section	.rdata$.refptr._ZSt3cin, "dr"
	.globl	.refptr._ZSt3cin
	.linkonce	discard
.refptr._ZSt3cin:
	.quad	_ZSt3cin
	.section	.rdata$.refptr._ZSt4cout, "dr"
	.globl	.refptr._ZSt4cout
	.linkonce	discard
.refptr._ZSt4cout:
	.quad	_ZSt4cout
